---
stages:
  - tests
  - builds
  - deploy

unit-test:
  stage: tests
  script:
    - ./test.sh
  tags:
    - ant31-builder

build-chart:
  stage: builds
  variables:
    HELM_HOME: /srv/.helm
    HELM: /srv/.helm/helm

  before_script:
    - "sed -ri \"s/version: 0.0.2/version: $CI_COMMIT_TAG/g\" chart/cookieapp/Chart.yaml"
    - cd chart/cookieapp
  script:
    - $HELM registry login -u "$QUAY_LOGIN" -p "$QUAY_PASS" quay.io
    - $HELM registry push --namespace ant31 -f quay.io
  tags:
    - ant31-builder
  only:
    - tags

build-image:
  stage: builds
  image: docker
  only:
    - tags
  script:
    - docker login -u="$QUAY_LOGIN" -p="$QUAY_PASS" quay.io
    - docker build --no-cache -t quay.io/ant31/cookieapp-image:$CI_COMMIT_TAG .
    - docker push quay.io/ant31/cookieapp-image:$CI_COMMIT_TAG
  tags:
    - ant31-builder

deploy-prod:
  stage: deploy
  script:
    - echo "Deploy to $CI_COMMIT_TAG to production server"
    - "curl -XPOST http://$APPR_BACKEND/api/v1/upgrade -d \"{\\\"package\\\": \\\"quay.io/ant31/cookieapp@$CI_COMMIT_TAG\\\",\\\"helm_opts\\\": [\\\"cookie1\\\", \\\"--install\\\", \\\"--recreate-pods\\\"]}\""

  environment:
    name: prod
    url: "https://cookieapp.kubespray.com"
  when: manual
  only:
    - tags
