---
stages:
  - tests
  - builds

variables:
  PATH: $PATH:$CI_PROJECT_DIR
  APPR_VERSION: 0.3.8-dev


unit-test:
  stage: tests
  script:
    - ./test.sh
  tags:
    - shell

build_chart:
  stage: builds
  before_script:
    - "sed -ri \"s/version: 0.0.2/version: $TRAVIS_TAG/g\" chart/cookieapp/Chart.yaml"
    - cd chart/cookieapp
  script:
    - helm registry login -u "$QUAY_LOGIN" -p "$QUAY_PASS" quay.io
    - helm registry push --namespace ant31 -f
  tags:
    - shell
  only:
    - tags

build_image:
  stage: builds
  only:
    - tags
  script:
    - docker login -u="$QUAY_LOGIN" -p="$QUAY_PASS" quay.io
    - docker build --no-cache -t quay.io/ant31/cookieapp-image:$CI_COMMIT_TAG .
    - docker push quay.io/ant31/cookieapp-image:$CI_COMMIT_TAG
  tags:
    - shell
