---
stages:
  - builds
  - tests
  - deploy

unit-test:
  stage: tests
  script:
    - ./test.sh
  tags:
    - ant31-builder

variables:
  VERSION: "0.0.3"

build-chart:
  stage: builds
  variables:
    HELM_HOME: /srv/.helm
    HELM: /srv/.helm/helm
  before_script:
    - echo ${CI_COMMIT_SHA:0:8}
    - cd chart/cookieapp
    - "sed -ri \"s/version: ${VERSION}/version: ${VERSION}-${CI_COMMIT_SHA:0:8}/g\" Chart.yaml"
    - cat Chart.yaml
  script:
    - $HELM registry login -u "$QUAY_LOGIN" -p "$QUAY_PASS" quay.io
    # - $HELM registry push --namespace ant31 quay.io
    # - $HELM registry push --namespace ant31  quay.io --channel stable
  tags:
    - ant31-builder

build-image:
  stage: builds
  image: docker
  only:
    - tags
  script:
    - docker login -u="$QUAY_LOGIN" -p="$QUAY_PASS" quay.io
    - docker build --no-cache -t quay.io/ant31/cookieapp-image:${CI_COMMIT_TAG:0:8} .
    - docker push quay.io/ant31/cookieapp-image:${CI_COMMIT_TAG:0:8}
  tags:
    - ant31-builder

deploy:
  stage: deploy
  script:
    - echo "Deploy to ${VERSION}-${CI_COMMIT_TAG:0:8} to production server"
    - "curl -XPOST http://$APPR_BACKEND/api/v1/upgrade -d \"{\\\"package\\\": \\\"quay.io/ant31/cookieapp@${VERSION}-${CI_COMMIT_TAG:0:8}\\\",\\\"helm_opts\\\": [\\\"cookie1\\\", \\\"--install\\\"]}\""
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: "https://cookieapp-${CI_COMMIT_TAG:0:8}.kubespray.com"
  when: manual
  only:
    - tags
