---
stages:
  - tests
  - builds

unit-test:
  stage: tests
  script:
    - ./test.sh
  tags:
    - shell

build_chart:
  stage: builds
  variables:
    HELM_HOME: /srv/.helm

  before_script:
    - "sed -ri \"s/version: 0.0.2/version: $CI_COMMIT_TAG/g\" chart/cookieapp/Chart.yaml"
    - cd chart/cookieapp
  script:
    - helm registry login -u "$QUAY_LOGIN" -p "$QUAY_PASS" quay.io
    - helm registry push --namespace ant31 -f
  tags:
    - shell
  only:
    - tags

build_image:
  stage: builds
  only:
    - tags
  script:
    - docker login -u="$QUAY_LOGIN" -p="$QUAY_PASS" quay.io
    - docker build --no-cache -t quay.io/ant31/cookieapp-image:$CI_COMMIT_TAG .
    - docker push quay.io/ant31/cookieapp-image:$CI_COMMIT_TAG
  tags:
    - shell

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to $CI_COMMIT_TAG to production server"
    - "curl -XPOST http://$APPR_BACKEND/api/v1/upgrade -d \"{\\\"package\\\": \\\"quay.io/ant31/cookieapp@$CI_COMMIT_TAG\\\",\\\"helm_opts\\\": [\\\"cookie1\\\", \\\"--install\\\", \\\"--recreate-pods\\\"]}\""

  environment:
    name: prod
    url: "https://cookieapp.kubespray.com"
  when: manual
  only:
    - tags
