apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cookieapp
  labels:
    heritage: helm
spec:
metadata:
  name: cookieapp
  labels:
    app: cookieapp
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cookieapp
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
        - name: cookieapp
          image: "quay.io/ant31/cookieapp-image:v{{ .Chart.Version }}"
          ports:
            - name: http
              containerPort: 80
